lib/ebae_web/router.ex
defmodule EbaeWeb.Router do
  use EbaeWeb, :router

  alias Ebae.Accounts

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Accounts.MaybeAuthenticated
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", EbaeWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index

    resources "/signin", SessionController, only: [:new, :create]

    delete "/signout", SessionController, :delete

    resources "/signup", RegistrationController, only: [:new, :create]
  end

  scope "/sell", EbaeWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/", SellController, :sell

    get "/sold", SellController, :sold

    resources "/", SellController, only: [:new, :create, :delete]

    get "/:id", SellController, :auction
  end

  scope "/buy", EbaeWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/", BuyController, :buy

    get "/bids", BuyController, :bids

    get "/won", BuyController, :won

    resources "/:id", BuyController, only: [:new, :create]
  end
end

lib/ebae_web/views/layout_view.ex
defmodule EbaeWeb.LayoutView do
  use EbaeWeb, :view

  alias EbaeWeb.Auth

  def authenticated?(conn) do
    Auth.authenticated?(conn)
  end
end

lib/ebae_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Ebae</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= if authenticated?(@conn) do %>
            <%= link "Sell", to: Routes.sell_path(@conn, :sell), class: "nav-link" %>
            <%= link "Buy", to: Routes.buy_path(@conn, :buy), class: "nav-link" %>
            <%= link "Sign out", to: Routes.session_path(@conn, :delete), method: :delete, class: "nav-link" %>
          <% else %>
            <%= link "Sign in", to: Routes.session_path(@conn, :new), class: "nav-link" %>
            <%= link "Register", to: Routes.registration_path(@conn, :new), class: "nav-link" %>
          <% end %>      
        </nav>
        <a href="/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/ebae.png") %>" alt="Ebae"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>